name: hello_words
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.1
  protobuf: ^3.1.0
  shelf: ^1.4.2
  shelf_proxy: ^1.0.4

dev_dependencies:
  protoc_plugin: ^21.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
